### ISSUE TITLE
Bugfixes

### ISSUE THREAD

**Issue by Karol-2** [Karol-2/Mercury-Project#135]
If you occur any bugs please write them here:

**Comment by Karol-2** [comment]
- [ ] Console problems with Paginator component

**Comment by gf-rog** [comment]
- [ ] Can't go to profile from the home page
- [ ] Editing the user is unintuitive
- [ ] The camera freezes when the other person leaves the meeting, should redirect back with a message
- [ ] Clicking the profile doesn't work, it's a separate button
